//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateInvoice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;districts&gt;&lt;district&gt;&lt;id&gt;1001&lt;/id&gt;&lt;name_th&gt;เขตพระนคร&lt;/name_th&gt;&lt;name_en&gt;Khet Phra Nakhon&lt;/name_en&gt;&lt;province_id&gt;1&lt;/province_id&gt;&lt;created_at&gt;2019-08-09T03:33:09.000+07:00&lt;/created_at&gt;&lt;updated_at&gt;2025-09-20T06:31:26.000+07:00&lt;/updated_at&gt;&lt;deleted_at /&gt;&lt;/district&gt;&lt;district&gt;&lt;id&gt;1002&lt;/id&gt;&lt;name_th&gt;เขตดุสิต&lt;/name_th&gt;&lt;name_en&gt;Khet Dusit&lt;/name_en&gt;&lt;province_id&gt;1&lt;/province_id&gt;&lt;created_at&gt;2019-08-09T03:33:09.000+07:00&lt;/created_at&gt;&lt;updated_at&gt;2025-09-20T06:31:26.000+07:00&lt;/updated_at&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string districts {
            get {
                return ResourceManager.GetString("districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;provinces&gt;&lt;province&gt;&lt;id&gt;1&lt;/id&gt;&lt;name_th&gt;กรุงเทพมหานคร&lt;/name_th&gt;&lt;name_en&gt;Bangkok&lt;/name_en&gt;&lt;geography_id&gt;2&lt;/geography_id&gt;&lt;created_at&gt;2019-08-09T03:33:09.000+07:00&lt;/created_at&gt;&lt;updated_at&gt;2025-09-20T06:31:26.000+07:00&lt;/updated_at&gt;&lt;deleted_at /&gt;&lt;/province&gt;&lt;province&gt;&lt;id&gt;2&lt;/id&gt;&lt;name_th&gt;สมุทรปราการ&lt;/name_th&gt;&lt;name_en&gt;Samut Prakan&lt;/name_en&gt;&lt;geography_id&gt;2&lt;/geography_id&gt;&lt;created_at&gt;2019-08-09T03:33:09.000+07:00&lt;/created_at&gt;&lt;updated_at&gt;2025-09-20T06:31:26.000+07:00&lt;/updated_at&gt;&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string provinces {
            get {
                return ResourceManager.GetString("provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;sub_districts&gt;&lt;sub_district&gt;&lt;id&gt;100101&lt;/id&gt;&lt;zip_code&gt;10200&lt;/zip_code&gt;&lt;name_th&gt;พระบรมมหาราชวัง&lt;/name_th&gt;&lt;name_en&gt;Phra Borom Maha Ratchawang&lt;/name_en&gt;&lt;district_id&gt;1001&lt;/district_id&gt;&lt;lat /&gt;&lt;long /&gt;&lt;created_at&gt;2019-08-09T03:33:09.000+07:00&lt;/created_at&gt;&lt;updated_at&gt;2025-09-20T06:31:26.000+07:00&lt;/updated_at&gt;&lt;deleted_at /&gt;&lt;/sub_district&gt;&lt;sub_district&gt;&lt;id&gt;100102&lt;/id&gt;&lt;zip_code&gt;10200&lt;/zip_code&gt;&lt;name_th&gt;วังบูรพาภิรมย์&lt;/name_th&gt;&lt;name_en&gt;Wang Burapha Phirom&lt;/name_en&gt;&lt;district_id&gt;10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sub_districts {
            get {
                return ResourceManager.GetString("sub_districts", resourceCulture);
            }
        }
    }
}
